### ISSUE TITLE
Not working for Kraken x31

### ISSUE THREAD

**Issue by dragonator4** [RBlafford/levd#1]
I arrived at `levd` from [jaksi/leviathan](https://github.com/jaksi/leviathan), from your last comment on [Issue #1](https://github.com/jaksi/leviathan/issues/1) of that project. The reason I am opening this issue, even though you have mentioned that `levd` is for Kraken x61, is that [`leviathan` works with Kraken x31](https://github.com/jaksi/leviathan/issues/5). I am guessing (hoping) that it would not be a ton of work to enable `levd` to work with Kraken x31 as well. Kraken x31 does not have LED lighting, that is the only difference between x31 and x41/x61, apart from the radiator size, but I guess radiator size does not affect `levd` in any way.

I had written a small Python script, executed on login, to make the fan speeds follow a curve. All that it did was keep resetting the previous speed value though `leviathan`, get the `liquid_temperature` value in exchange, and interpolate using a dict of target temperature and fan speeds. Then I saw that jaksi had a branch with a driver, and you had this. So I decided to give your program a shot, because it has temperature-based-fan-control enabled, and because it is a daemon.

It would be simply awesome if you could enable support for Kraken x31. I am willing to test your work for you. Also, if it is a quick fix in the files before `cmake`/`make`, I can change that on my machine and report back almost immediately. Thank you!

**Comment by RBlafford** [comment]
So in the other thread you mentioned that the daemon was working with the Kraken x31, is this still the case?

**Comment by RBlafford** [comment]
Odd because Jrudess's fork only contains a single commit for using liquid temp instead of cpu temp. However since his changes have now been merged I will close this PR.
