### ISSUE TITLE
Inaccurate CPU Temp Reading

### ISSUE THREAD

**Issue by fabiangambino** [RBlafford/levd#10]
I'm running Fedora 29 and running levd for my kraken x61. I'm not getting an accurate reading of my CPU temp when running : cat /sys/class/hwmon/hwmon0/temp1_input

I get a constant 27800 reading when both idle and when compiling. I have xSensors running in the background showing me that my CPU temp gets up to 44C while compiling. Because the levd.cfg uses a default temperature source of cpu, and the temp reading is inaccurately at a constant of 27800, my kraken fans will never spin faster.

I changed the temperature source to "liquid" in levd.cfg, which works, however, it takes a long time for liquid to change temperature which is impractical. I was compiling running on all 8 threads and the liquid temp only increased by 1C for several seconds.

The ideal solution is to figure out why my cpu temp reading is incorrect. If I can get an accurate reading, I can use cpu as the temp source allowing me to have accelerated fan speeds based on cpu temp.

**Comment by RBlafford** [comment]
Thanks for reporting this! I will take a look now, going to maybe introduce a dependency that will give a good consistent temperature reading that is cross-platform as well

**Comment by RBlafford** [comment]
@fabiangambino can you take a look at PR #13? I introduced a change to get temperature readings from the lmsensors library instead of reading from the sysfs interface. Should support more platforms as well. Compile and re-run the driver and see if your still seeing those consistent CPU temperature readings.

**Comment by RBlafford** [comment]
Sweet glad to help!
