### ISSUE TITLE
Any chance of supporting fan profiles based on liquid temperature?

### ISSUE THREAD

**Issue by goncalossilva** [RBlafford/levd#2]
As the title says, basing the fan curve on the liquid temp, not the CPU temp.

**Comment by jrudess** [comment]
Saw this issue, so went ahead and committed my changes for this to my fork here:
https://github.com/jrudess/levd

This should probably be made controllable in the config file.  I've also been wondering if there is use in using both cpu and liquid temperatures in the fan control.

**Comment by goncalossilva** [comment]
Looks good! I'll try it out.

> This should probably be made controllable in the config file.

This would make sense. CAM (:man_facepalming:) works like this, letting you choose either CPU, Liquid or GPU temp as the source for the fan curves.

> This should probably be made controllable in the config file. I've also been wondering if there is value in using both the cpu and liquid temperatures in the fan control.

Indeed, ideally this would be up to the user.

**Comment by goncalossilva** [comment]
Based off of @jrudess's work, got a bit carried away: https://github.com/goncalossilva/levd/tree/ft.liquid_temp

I'm unsure if @RBlafford would want a PR of this given there are a few additional changes, namely removal of unused parameters and a refactor of how the main loop works: liquid temperature is not available until an update is sent, so color is going first and only then go the speeds.

Besides the `temperature_source` config option, there's also `interval`. For liquid-based configurations an update rate of 500ms is a bit unecessary (I'm personally using 2000ms).

Finally, I haven't touched C++ in many years, so I'm not very confident in the code quality. Still, testing locally has yielded good results and I'm now using this.

Leaving the issue open for now.

**Comment by jrudess** [comment]
I like the additional changes!   I'm not as sure about the cmake changes for /usr/bin vs /bin.  I maintain the Aurchlinx package for levd on the AUR, and had been installing the binary to /usr/bin with:

    `cmake -DCMAKE_INSTALL_PREFIX="/usr" ..`

**Comment by goncalossilva** [comment]
Oh, I see. To be honest I am generally unaware of how cmake actually works, and just made this change because the installation was broken under Fedora. I wasn't planning to include in the PR, should I make it. Given there's `DCMAKE_INSTALL_PREFIX` I'll happily remove the change. Thanks @jrudess!

**Comment by dragonator4** [comment]
@jrudess New Arch user here. Great work on the AUR package! It made installation a breeze. I use Kraken X31, but they share the same USB config, so this just seems to work for my device as well, although I have not tested a high workload to ensure the fan and pump increase speeds.

Sorry for cross-posting, but can either of you or @goncalossilva quickly answer [this question](https://github.com/RBlafford/levd/issues/4) I posted on the @RBlafford master branch? I would really appreciate it.

**Comment by goncalossilva** [comment]
Sorry, I no longer recall the codebase, but one thing you could do is look through the code and pinpoint where things are being read from.

**Comment by dragonator4** [comment]
I tried that, but I am not very literate in CPP to understand much of it. I think the file is `kDefaultCPUTempFile`, but I cannot find it's path. I think the main work is being done here:

```
  // Open config file and handle to thermal monitor
  auto          config_opts = parse_config_file(kDefaultConfigFile);
  std::ifstream istream(kDefaultCPUTempFile);
  LOG_IF(FATAL, !istream.good()) << "Could not open: " << kDefaultCPUTempFile;
  uint32_t cpu_temp           = 0;
  uint32_t liquid_temp        = 0;
  uint32_t old_fan_speed      = 0;
  time_t   last_time_modified = std::numeric_limits<time_t>::min();
```

Also, in the `while` loop:

```
  // Grab latest cpu temperature
    istream >> cpu_temp;
    istream.seekg(0);

    cpu_temp = cpu_temp / 1000;

    // Grab latest parameters, if they've been changed
    if (file_is_modified(kDefaultConfigFile, last_time_modified)) {
      LOG(INFO)
        << "Detected modifications to config file, updating preferences...";
      config_opts        = parse_config_file(kDefaultConfigFile);
      last_time_modified = time(0);
    }

    // Based on parameters and current CPU temp, set desired kraken settings
    auto next = next_speed(config_opts.ftp_, liquid_temp);
    if (abs(next - old_fan_speed) <= old_fan_speed * 0.1) {
      next = old_fan_speed;
    }
    VLOG(2) << "Current CPU Temperature: " << cpu_temp << "C";
    VLOG(2) << "Current Liquid Temperature: " << liquid_temp << "C";
    VLOG(2) << "Setting fan speed: " << next;
```

Where is this coming from?

**Comment by dragonator4** [comment]
Yes perfect! I figured the file path was defined in `constants.h`. I changed it to my `coretemp` `hwmon` location, so the CPU temperature is correct.

I also figured that the speeds, set percentage and temperatures are directly used from the driver. So I'm trying to add a line that writes that data to a file in `/etc/leviathan/` (right after logging to journalctl), from where I can `cat` it into Conky. The specified file is being created, but its empty. I need to brush up my very rusty CPP to get it right...

**Comment by RBlafford** [comment]
@goncalossilva @jrudess @dragonator4 Hello all! I disabled emails a while back, and I honestly had NO idea there was this much conversation on a personal github repo of mine. I will check out all of these comments and address them individually

**Comment by RBlafford** [comment]
Yup PR looks good to me, just gave it a once over

**Comment by RBlafford** [comment]
Closing this issue since the liquid temperature feature has been merged!

**Comment by jrudess** [comment]
@rblafford Thanks for releasing this great tool!  Looks like my commit has been merged and I need to work on getting the archlinux AUR package (levd-git) pointing back to this tree! :-)
